#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/nest/anaconda3/envs/allen_inst_bkmt"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/nest/anaconda3/envs/allen_inst_bkmt/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/nest/Desktop/final_model_Fig6/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
